server:
  port:
    8080

spring:
  application:
    name:
      site

management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    export:
      prometheus:
        enable: true