server:
  port: 8080

links:
  path: http://localhost:8080/page/
  characters: https://rickandmortyapi.com/api/character
  transfer: http://localhost:8081/transfer

spring:
  devtools:
    restart:
      enabled: true

