server:
  port:
    8765

spring:
  application:
    name:
      cloud
  cloud:
    gateway:
      routes:
        - id: site
          uri: http://localhost:8080/
          predicates:
            - Path=/site/**
        - id: notes
          uri: http://localhost:8081/
          predicates:
            - Path=/notes/**