
server:
  port: 18090

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000

#server:
#  port: 38080
#
##spring:
##  security:
##    oauth2:
##      resourceserver:
##        jwt:
##          issuer-uri: http://localhost:38080